//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;

export type TestsBasicLiteral1Payload = undefined;
export type TestsBasicLiteral1Factory = () => undefined;
