//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;

export type TestsBasicLiteralTruePayload = true;
export const TestsBasicLiteralTrueFactory = () => true;
