//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;

export interface TestsBasicTestOptionalFieldPayload {
  optional: string | null | typeof undefined;
}
export const TestsBasicTestOptionalFieldFactory: () => TestsBasicTestOptionalFieldPayload = () => ({
  optional: (() => null)()
});
