//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;
import type { TestsBasicTestStructInnerPayload as CodegenTestsBasicTestStructInnerPayload } from "./TestStructInner";
import { TestsBasicTestStructInnerFactory as CodegenTestsBasicTestStructInnerFactory } from "./TestStructInner";

export interface TestsBasicTestStructPayload {
  a: string;
  b: number;
  c: CodegenTestsBasicTestStructInnerPayload;
}
export const TestsBasicTestStructFactory: () => TestsBasicTestStructPayload = () => ({
  a: (() => "")(),
  b: (() => 0)(),
  c: CodegenTestsBasicTestStructInnerFactory()
});
