//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;
import type { TestsBasicTestAtleastOnePayload as CodegenTestsBasicTestAtleastOnePayload } from "./TestAtleastOne";

export interface TestsBasicTestListOfListStructPayload {
  list_of_list: Array<CodegenTestsBasicTestAtleastOnePayload>;
}
export const TestsBasicTestListOfListStructFactory: () => TestsBasicTestListOfListStructPayload = () => ({
  list_of_list: (() => [])()
});
