//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
import type { TestsBasicTestKindPayload as CodegenTestsBasicTestKindPayload } from "./TestKind";

export type TestsBasicTestAtleastOnePayload = Array<CodegenTestsBasicTestKindPayload>;

export const TestsBasicTestAtleastOneFactory = () => [];
