//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.

export interface TestsBasicTestStructInnerPayload {
  d: boolean;
  e: number;
  f: number;
}

export const TestsBasicTestStructInnerFactory: () => TestsBasicTestStructInnerPayload = () => ({
  d: (() => false)(),
  e: (() => 0)(),
  f: (() => 0)()
});
