//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.

export type TestsBasicTestEnumPayload = "a" | "b" | "c";

export const TestsBasicTestEnumFactory: () => TestsBasicTestEnumPayload = () =>
  "a";
