// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { TestsBasicTestAtleastOneType as CodegenTestsBasicTestAtleastOneType } from "../../tests/basic/TestAtleastOne";
import { TestsBasicTestEnumType as CodegenTestsBasicTestEnumType } from "../../tests/basic/TestEnum";
import { TestsBasicTestKindType as CodegenTestsBasicTestKindType } from "../../tests/basic/TestKind";
import { AllRequiredListOfTestKindType as CodegenAllRequiredListOfTestKindType } from "./ListOfTestKind";
import { TestsBasicTestListOfListStructType as CodegenTestsBasicTestListOfListStructType } from "../../tests/basic/TestListOfListStruct";
import { TestsBasicTestLiteralStructType as CodegenTestsBasicTestLiteralStructType } from "../../tests/basic/TestLiteralStruct";
import { TestsBasicTestLiteralTopType as CodegenTestsBasicTestLiteralTopType } from "../../tests/basic/TestLiteralTop";
import { TestsBasicTestMapType as CodegenTestsBasicTestMapType } from "../../tests/basic/TestMap";
import { TestsBasicTestOptionalFieldType as CodegenTestsBasicTestOptionalFieldType } from "../../tests/basic/TestOptionalField";
import { TestsBasicTestStructType as CodegenTestsBasicTestStructType } from "../../tests/basic/TestStruct";
import { AllRequiredTripletOfSideImport2Type as CodegenAllRequiredTripletOfSideImport2Type } from "./TripletOfSideImport2";
import { GraphQLObjectType } from "graphql";

export const AllRequiredAssembledFields = {
  test_atleast_one: CodegenTestsBasicTestAtleastOneType,

  test_enum: CodegenTestsBasicTestEnumType,

  test_kind: CodegenTestsBasicTestKindType,

  test_list_of: CodegenAllRequiredListOfTestKindType,

  test_list_of_list_struct: CodegenTestsBasicTestListOfListStructType,

  test_literal_struct: CodegenTestsBasicTestLiteralStructType,

  test_literal_top: CodegenTestsBasicTestLiteralTopType,

  test_map: CodegenTestsBasicTestMapType,

  test_optional_field: CodegenTestsBasicTestOptionalFieldType,

  test_struct: CodegenTestsBasicTestStructType,

  test_triplet: CodegenAllRequiredTripletOfSideImport2Type
};
export const AllRequiredAssembledType = new GraphQLObjectType({
  name: "AllRequiredAssembledType",
  description: "",
  fields: { ...AllRequiredAssembledFields }
});
