// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.
import { TestsBasicTestAtleastOneType as CodegenTestsBasicTestAtleastOneType } from "../../tests/basic/TestAtleastOne";
import { TestsBasicTestEnumType as CodegenTestsBasicTestEnumType } from "../../tests/basic/TestEnum";
import { TestsBasicTestKindType as CodegenTestsBasicTestKindType } from "../../tests/basic/TestKind";
import { AllRequiredListOfTestKindType as CodegenAllRequiredListOfTestKindType } from "./ListOfTestKind";
import { TestsBasicTestListOfListStructType as CodegenTestsBasicTestListOfListStructType } from "../../tests/basic/TestListOfListStruct";
import { TestsBasicTestLiteralStructType as CodegenTestsBasicTestLiteralStructType } from "../../tests/basic/TestLiteralStruct";
import { TestsBasicTestLiteralTopType as CodegenTestsBasicTestLiteralTopType } from "../../tests/basic/TestLiteralTop";
import { TestsBasicTestMapType as CodegenTestsBasicTestMapType } from "../../tests/basic/TestMap";
import { TestsBasicTestOptionalFieldType as CodegenTestsBasicTestOptionalFieldType } from "../../tests/basic/TestOptionalField";
import { TestsBasicTestStructType as CodegenTestsBasicTestStructType } from "../../tests/basic/TestStruct";
import { AllRequiredTripletOfSideImport2Type as CodegenAllRequiredTripletOfSideImport2Type } from "./TripletOfSideImport2";

export const AllRequiredAssembledFields = {
  test_atleast_one: {
    type: CodegenTestsBasicTestAtleastOneType,
    description: ""
  },
  test_enum: { type: CodegenTestsBasicTestEnumType, description: "" },
  test_kind: { type: CodegenTestsBasicTestKindType, description: "" },
  test_list_of: { type: CodegenAllRequiredListOfTestKindType, description: "" },
  test_list_of_list_struct: {
    type: CodegenTestsBasicTestListOfListStructType,
    description: ""
  },
  test_literal_struct: {
    type: CodegenTestsBasicTestLiteralStructType,
    description: ""
  },
  test_literal_top: {
    type: CodegenTestsBasicTestLiteralTopType,
    description: ""
  },
  test_map: { type: CodegenTestsBasicTestMapType, description: "" },
  test_optional_field: {
    type: CodegenTestsBasicTestOptionalFieldType,
    description: ""
  },
  test_struct: { type: CodegenTestsBasicTestStructType, description: "" },
  test_triplet: {
    type: CodegenAllRequiredTripletOfSideImport2Type,
    description: ""
  }
};
