// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.
import { TestsBasicTestKindType as CodegenTestsBasicTestKindType } from "../../tests/basic/TestKind";
import { GraphQLList } from "graphql";

export const AllRequiredListOfTestKindType = new GraphQLList(
  CodegenTestsBasicTestKindType
);

export const AllRequiredListOfTestKindInputType = new GraphQLList(
  CodegenTestsBasicTestKindType
);
