// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import {
  TestsAbsThreeSideImport2Type as CodegenTestsAbsThreeSideImport2Type,
  TestsAbsThreeSideImport2InputType as CodegenTestsAbsThreeSideImport2InputType
} from "../../tests/abs/three/SideImport2";
import {
  GraphQLList,
  GraphQLObjectType,
  GraphQLInputObjectType
} from "graphql";
import { TestsBasicTestLiteralTopType as CodegenTestsBasicTestLiteralTopType } from "../../tests/basic/TestLiteralTop";
import { Anything } from "../../__idol_graphql__";

export const AllRequiredTripletOfSideImport2Fields = {
  a: CodegenTestsAbsThreeSideImport2Type,

  b: new GraphQLList(CodegenTestsBasicTestLiteralTopType),

  c: Anything
};
export const AllRequiredTripletOfSideImport2Type = new GraphQLObjectType({
  name: "AllRequiredTripletOfSideImport2Type",
  description: "",
  fields: { ...AllRequiredTripletOfSideImport2Fields }
});
export const AllRequiredTripletOfSideImport2InputFields = {
  a: CodegenTestsAbsThreeSideImport2InputType,

  b: new GraphQLList(CodegenTestsBasicTestLiteralTopType),

  c: Anything
};
export const AllRequiredTripletOfSideImport2InputType = new GraphQLInputObjectType(
  {
    name: "AllRequiredTripletOfSideImport2InputType",
    description: "",
    fields: { ...AllRequiredTripletOfSideImport2InputFields }
  }
);
