// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import {
  TestsAbsThreeSideImport2Type as CodegenTestsAbsThreeSideImport2Type,
  TestsAbsThreeSideImport2InputType as CodegenTestsAbsThreeSideImport2InputType
} from "../../tests/abs/three/SideImport2";
import { TestsBasicTestLiteralTopType as CodegenTestsBasicTestLiteralTopType } from "../../tests/basic/TestLiteralTop";
import {
  GraphQLList,
  GraphQLObjectType,
  GraphQLInputObjectType
} from "graphql";
import { Anything } from "../../__idol_graphql__";

export const AllRequiredTripletOfSideImport2Fields = {
  a: { type: CodegenTestsAbsThreeSideImport2Type, description: "" },
  b: {
    type: new GraphQLList(CodegenTestsBasicTestLiteralTopType),
    description: ""
  },
  c: { type: Anything, description: "" }
};
export const AllRequiredTripletOfSideImport2Type = new GraphQLObjectType({
  name: "AllRequiredTripletOfSideImport2",
  description: "",
  fields: { ...AllRequiredTripletOfSideImport2Fields }
});
export const AllRequiredTripletOfSideImport2InputFields = {
  a: { type: CodegenTestsAbsThreeSideImport2InputType, description: "" },
  b: {
    type: new GraphQLList(CodegenTestsBasicTestLiteralTopType),
    description: ""
  },
  c: { type: Anything, description: "" }
};
export const AllRequiredTripletOfSideImport2InputType = new GraphQLInputObjectType(
  {
    name: "AllRequiredTripletOfSideImport2Input",
    description: "",
    fields: { ...AllRequiredTripletOfSideImport2InputFields }
  }
);
