import {
    Enum as Enum_,
    Struct as Struct_,
    List as List_,
    Map as Map_,
    Literal as Literal_,
    Primitive as Primitive_,
} from "__idol__"
import * as declarations from "declarations"
// DO NOT EDIT THIS FILE
// This file is generated via idol_js.js.  You can either subclass these types
// in your own module file or update the relevant model.toml file and regenerate.


export function TypeDec(val) {
    return TypeDec.wrap.apply(this, arguments)
}

Struct_(TypeDec, {
    enum: ["enum", Primitive_.of("string")],
    fields: ["fields", FieldDec],
    isA: ["is_a", Primitive_.of("string")],
    tags: ["tags", Primitive_.of("string")],
    typeVars: ["type_vars", Primitive_.of("string")],
})

Struct_(TypeDec);
TypeDec.metadata = {"dependencies":[{"from":{"module_name":"declarations","qualified_name":"declarations.TypeDec","type_name":"TypeDec"},"to":{"module_name":"declarations","qualified_name":"declarations.FieldDec","type_name":"FieldDec"},"is_abstraction":false,"is_local":true}],"fields":{"is_a":{"field_name":"is_a","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"string","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Scalar"}},"fields":{"field_name":"fields","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"int53","reference":{"module_name":"declarations","qualified_name":"declarations.FieldDec","type_name":"FieldDec"},"struct_kind":"Map"}},"type_vars":{"field_name":"type_vars","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"string","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Repeated"}},"tags":{"field_name":"tags","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"string","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Repeated"}},"enum":{"field_name":"enum","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"string","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Repeated"}}},"is_a":null,"named":{"module_name":"declarations","qualified_name":"declarations.TypeDec","type_name":"TypeDec"},"options":[],"tags":[],"type_vars":[]};

