/*
DO NOT EDIT
This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
*/
import { SchemaLiteral as SchemaLiteral_ } from "";
export class SchemaLiteral {
  constructor(val) {
    this._original = val;
  }
  /*
These methods are implemented via the runtime, stubs exist here for reference.
*/

  static validate(val) {}
  static isValid(val) {
    return true;
  }
  static expand(val) {
    return val;
  }
  static unwrap(val) {
    return val;
  }
  static wrap(val) {
    return null;
  }
}
export class Literal extends SchemaLiteral_ {
  constructor(val) {
    super(val);
  }
}
