/*
DO NOT EDIT
This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
*/
import { Enum } from "../../__idol__.js";
export const SchemaPrimitiveType = {
  INT: "int",
  DOUBLE: "double",
  STRING: "string",
  BOOL: "bool",
  ANY: "any",
  options: ["int", "double", "string", "bool", "any"],
  default: "int",
  validate(val) {},
  isValid(val) {
    return true;
  },
  expand(val) {
    return val;
  },
  expand(wrap) {
    return val;
  },
  expand(unwrap) {
    return val;
  }
};
Enum(SchemaPrimitiveType);
