/*
DO NOT EDIT
This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
*/
import { Enum } from "../../__idol__.js";
export const SchemaStructKind = {
  SCALAR: "Scalar",
  REPEATED: "Repeated",
  MAP: "Map",
  options: ["Scalar", "Repeated", "Map"],
  default: "Scalar",
  validate(val) {},
  isValid(val) {
    return true;
  },
  expand(val) {
    return val;
  },
  expand(wrap) {
    return val;
  },
  expand(unwrap) {
    return val;
  }
};
Enum(SchemaStructKind);
