/*
DO NOT EDIT
This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
*/
import { SchemaType as SchemaType_ } from "";
export class SchemaType {
  constructor(val) {
    this._original = val;
  }
  /*
These methods are implemented via the runtime, stubs exist here for reference.
*/

  static validate(val) {}
  static isValid(val) {
    return true;
  }
  static expand(val) {
    return val;
  }
  static unwrap(val) {
    return val;
  }
  static wrap(val) {
    return null;
  }
}
export class Type extends SchemaType_ {
  constructor(val) {
    super(val);
  }
}
