if: tag IS blank
sudo: false
language: rust
rust: stable
os:
- linux
- osx
cache:
  directories:
  - "$HOME/.cargo"
addons:
  apt:
    update: true
    sources:
    - deadsnakes
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - jq
    - python3.6
  homebrew:
    update: true
    packages:
    - jq
    - node@8
script:
- |
  set -e
  export PATH="$PWD/test:$PATH"
  export PATH="/usr/local/opt/node@8/bin:$PATH"
  export PATH="$PWD/node_modules/.bin:$PATH"
  npm install
  make test
  make release

  mkdir bin
  mkdir release

  for file in ./target/release/*; do
    test -x $file && test -f $file && cp $file bin/
  done

  for file in ./src/bin/*; do
    test -x $file && test -f $file && cp $file bin/
  done

  cp -r ./src/lib ./

  tar c bin lib | gzip > release/idol-$(uname | tr '[:upper:]' '[:lower:]')-$(uname -m).tar.gz
before_deploy:
- git config --local user.name "Zachary Collins"
- git config --local user.email "recursive.cookie.jar@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-v$(./bin/idol --version | cut -d'' '' -f2).$(git log --format=%h -1)}
- git tag $TRAVIS_TAG || git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: MKiNVxhgyi9oGVBAAuemny3wc8jjOaeP55dR35/QbQDbb5AmRj4Fpc4VttT2+TQbnFB7VawnvI/HyGt53FverzODBmxGsGf7slDp6Qvlz5mVsWmGrS+5x9ok03hOAAtZKB1GL+O+Qf/A5jQuoCwYdQCw/UBGVS7Edud/bEvAvsMur6uy5qoboq8CCJie8MSFjxGFanf4pdO5NuCEjc33bjfSI4XyHrl2xC7oPSmTWM9ZsHO6UOm6pah0wia08D4r8Hc6iTTr9Uqszt1pUdjvJk7qZ35c5zOrr1G+pLXHGUefMqpCY1KHQwSEjvzXWekKBITJC1EnRFDTValB2LPPx0XsewTIB2Siydq3bI4ij71iSoQE91o6Mx11VS6Z50fvMtSnAMp1+CfJNkeicqLC+HXBiIWhjuFFzNFMXtnMoADvAU7iNtZF8skLNY6XwtsOyyeB41CfjEIe4U6WKcwy/YbY+mzPlhvCgFc6tm4YU2juU5JvBy52vUHYbArHcV7U10Fn0Zpca6ZG6M8wXEQzjNzm+0quTRb2ETSoJzR0j3sYRzkRGONVarYWsfZlXt4Qiy7T8CDMfVsQgPWrcArkw+Mc4ETrMDiigJwC2kcKxumOyoiaAvuooo840h6B94xv+hy4zm3eRQjCSMyWfCpivrJfMR8lkL55Jsb8Fk2YhQA=
  file_glob: true
  file: release/*
  on:
    repo: lyric-com/idol
