// This file was scaffolded by idol_graphql.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql.;
import { GraphQLObjectType } from "graphql";
import { SchemaFieldFields } from "../codegen/schema/Field";

export const FieldType = new GraphQLObjectType({
  name: "FieldType",
  description: "",
  fields: { ...SchemaFieldFields }
});
