// This file was scaffolded by idol_graphql.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql.;
import { GraphQLObjectType } from "graphql";
import { SchemaLiteralFields } from "../codegen/schema/Literal";

export const LiteralType = new GraphQLObjectType({
  name: "LiteralType",
  description: "",
  fields: { ...SchemaLiteralFields }
});
