"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.PrimitiveTypeType = void 0;

var _PrimitiveType = require("../codegen/schema/PrimitiveType");

// This file was scaffolded by idol_graphql.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql.;
var PrimitiveTypeType = _PrimitiveType.SchemaPrimitiveTypeType;
exports.PrimitiveTypeType = PrimitiveTypeType;