// This file was scaffolded by idol_graphql.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql.;
import { GraphQLObjectType } from "graphql";
import { SchemaTypeFields } from "../codegen/schema/Type";

export const TypeType = new GraphQLObjectType({
  name: "TypeType",
  description:
    "A wrapper type containing fields that can describe a Type, as well as its tag metadata.",
  fields: { ...SchemaTypeFields }
});
