# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, Primitive
from ...schema.reference import Reference as ScaffoldReference


class SchemaDependency(Struct):
    from_: ScaffoldReference
    is_abstraction: bool
    is_local: bool
    to: ScaffoldReference
    __field_constructors__ = [
        ("from", "from_", ScaffoldReference),
        ("is_abstraction", "is_abstraction", Primitive(bool)),
        ("is_local", "is_local", Primitive(bool)),
        ("to", "to", ScaffoldReference),
    ]
