# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, Primitive
from ...schema.reference import Reference as ScaffoldReference


class SchemaDependency(Struct):
    from_: ScaffoldReference
    is_abstraction: bool
    is_local: bool
    to: ScaffoldReference
    __field_constructors__ = [
        ("from", "from_", ScaffoldReference, dict(optional=False)),
        ("is_abstraction", "is_abstraction", Primitive.of(bool), dict(optional=False)),
        ("is_local", "is_local", Primitive.of(bool), dict(optional=False)),
        ("to", "to", ScaffoldReference, dict(optional=False)),
    ]
