# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, Primitive, List as List_
from typing import List
from ...schema.type_struct import TypeStruct as ScaffoldTypeStruct


class SchemaField(Struct):
    field_name: str
    tags: List[str]
    type_struct: ScaffoldTypeStruct
    __field_constructors__ = [
        ("field_name", "field_name", Primitive(str)),
        ("tags", "tags", List_.of(Primitive(str))),
        ("type_struct", "type_struct", ScaffoldTypeStruct),
    ]
