# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ....__idol__ import Struct, Primitive


class SchemaLiteral(Struct):
    bool: bool
    double: float
    int: int
    string: str
    __field_constructors__ = [
        ("bool", "bool", Primitive.of(bool)),
        ("double", "double", Primitive.of(float)),
        ("int", "int", Primitive.of(int)),
        ("string", "string", Primitive.of(str)),
    ]
