# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from enum import Enum
from ..__idol__ import Enum as Enum_


class SchemaPrimitiveType(Enum, Enum_):
    INT = "int"
    DOUBLE = "double"
    STRING = "string"
    BOOL = "bool"
    ANY = "any"
