# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, Primitive


class SchemaReference(Struct):
    module_name: str
    qualified_name: str
    type_name: str
    __field_constructors__ = [
        ("module_name", "module_name", Primitive(str)),
        ("qualified_name", "qualified_name", Primitive(str)),
        ("type_name", "type_name", Primitive(str)),
    ]
