# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ....__idol__ import Enum


class SchemaStructKind(Enum):
    SCALAR = "Scalar"
    REPEATED = "Repeated"
    MAP = "Map"
