# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, List, Map, Primitive
from typing import MutableSequence, MutableMapping, Optional
from ...schema.dependency import Dependency as ScaffoldDependency
from ...schema.field import Field as ScaffoldField
from ...schema.type_struct import TypeStruct as ScaffoldTypeStruct
from ...schema.reference import Reference as ScaffoldReference


class SchemaType(Struct):
    dependencies: MutableSequence[ScaffoldDependency]
    fields: MutableMapping[str, ScaffoldField]
    is_a: Optional[ScaffoldTypeStruct]
    named: ScaffoldReference
    options: MutableSequence[str]
    tags: MutableSequence[str]
    type_vars: MutableSequence[str]
    __field_constructors__ = [
        (
            "dependencies",
            "dependencies",
            List.of(ScaffoldDependency, dict(atleast_one=False)),
            dict(optional=False),
        ),
        (
            "fields",
            "fields",
            Map.of(ScaffoldField, dict(atleast_one=False)),
            dict(optional=False),
        ),
        ("is_a", "is_a", ScaffoldTypeStruct, dict(optional=True)),
        ("named", "named", ScaffoldReference, dict(optional=False)),
        (
            "options",
            "options",
            List.of(Primitive.of(str), dict(atleast_one=False)),
            dict(optional=False),
        ),
        (
            "tags",
            "tags",
            List.of(Primitive.of(str), dict(atleast_one=False)),
            dict(optional=False),
        ),
        (
            "type_vars",
            "type_vars",
            List.of(Primitive.of(str), dict(atleast_one=False)),
            dict(optional=False),
        ),
    ]
