# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ..__idol__ import Struct, List
from typing import Optional, MutableSequence
from ...schema.literal import Literal as ScaffoldLiteral
from ...schema.reference import Reference as ScaffoldReference
from ...schema.primitive_type import PrimitiveType as ScaffoldPrimitiveType
from ...schema.struct_kind import StructKind as ScaffoldStructKind


class SchemaTypeStruct(Struct):
    literal: Optional[ScaffoldLiteral]
    parameters: MutableSequence[ScaffoldReference]
    primitive_type: ScaffoldPrimitiveType
    reference: ScaffoldReference
    struct_kind: ScaffoldStructKind
    __field_constructors__ = [
        ("literal", "literal", ScaffoldLiteral, dict(optional=True)),
        (
            "parameters",
            "parameters",
            List.of(ScaffoldReference, dict(atleast_one=False)),
            dict(optional=False),
        ),
        (
            "primitive_type",
            "primitive_type",
            ScaffoldPrimitiveType,
            dict(optional=False),
        ),
        ("reference", "reference", ScaffoldReference, dict(optional=False)),
        ("struct_kind", "struct_kind", ScaffoldStructKind, dict(optional=False)),
    ]
