// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaModule } from "../codegen/schema/Module";

export class Module extends SchemaModule {
  constructor(val) {
    super(val);
  }
}
