// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaReference } from "../codegen/schema/Reference";

export class Reference extends SchemaReference {
  constructor(val) {
    super(val);
  }
}
