// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaStructKind } from "../codegen/schema/StructKind";

export const StructKind = SchemaStructKind;
