// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaTypeStruct } from "../codegen/schema/TypeStruct";
import { PrimitiveType } from "./PrimitiveType";

export class TypeStruct extends SchemaTypeStruct {
  constructor(val) {
    super(val);
  }

  get isPrimitive() {
    return !this.isAlias && !this.isLiteral;
  }

  get isAlias() {
    return !!this.reference.typeName;
  }

  get isLiteral() {
    return !!this.literal;
  }

  get literalValue(): ?(string | number | boolean) {
    if (this.literal != null) {
      switch (this.primitiveType) {
        case PrimitiveType.STRING:
          return this.literal.string;
        case PrimitiveType.DOUBLE:
          return this.literal.double;
        case PrimitiveType.BOOL:
          return this.literal.bool;
        case PrimitiveType.INT:
          return this.literal.int;
      }
    }
  }
}
