// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaField } from "../codegen/schema/Field";

export class Field extends SchemaField {
  constructor(val) {
    super(val);
  }
}
