"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.PrimitiveType = void 0;

var _PrimitiveType = require("../codegen/schema/PrimitiveType");

// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
var PrimitiveType = _PrimitiveType.SchemaPrimitiveType;
exports.PrimitiveType = PrimitiveType;