// This file was scaffolded by idol_js.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_js.;
import { SchemaType } from "../codegen/schema/Type";

export class Type extends SchemaType {
  constructor(val) {
    super(val);
  }

  withTags(tags: string[]): Type {
    const newType = new Type(JSON.parse(JSON.stringify(Type.unwrap(this))));
    newType.tags = tags;
    return newType;
  }
}
