"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaLiteralFactory = void 0;

// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
var SchemaLiteralFactory = function SchemaLiteralFactory() {
  return {
    bool: function () {
      return false;
    }(),
    "double": function () {
      return 0;
    }(),
    "int": function () {
      return 0;
    }(),
    string: function () {
      return "";
    }()
  };
};

exports.SchemaLiteralFactory = SchemaLiteralFactory;