"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaModuleFactory = void 0;

// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
var SchemaModuleFactory = function SchemaModuleFactory() {
  return {
    module_name: function () {
      return "";
    }(),
    types_by_name: function () {
      return {};
    }(),
    types_dependency_ordering: function () {
      return [];
    }()
  };
};

exports.SchemaModuleFactory = SchemaModuleFactory;