"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaPrimitiveTypeFactory = exports.SchemaPrimitiveType = void 0;
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
var SchemaPrimitiveType = {
  INT: "int",
  DOUBLE: "double",
  STRING: "string",
  BOOL: "bool",
  ANY: "any"
};
exports.SchemaPrimitiveType = SchemaPrimitiveType;

var SchemaPrimitiveTypeFactory = function SchemaPrimitiveTypeFactory() {
  return "int";
};

exports.SchemaPrimitiveTypeFactory = SchemaPrimitiveTypeFactory;