"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaTypeStructFactory = void 0;

var _PrimitiveType = require("../../schema/PrimitiveType");

var _Reference = require("../../schema/Reference");

var _StructKind = require("../../schema/StructKind");

// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
var SchemaTypeStructFactory = function SchemaTypeStructFactory() {
  return {
    literal: function () {
      return null;
    }(),
    primitive_type: (0, _PrimitiveType.PrimitiveTypeFactory)(),
    reference: (0, _Reference.ReferenceFactory)(),
    struct_kind: (0, _StructKind.StructKindFactory)()
  };
};

exports.SchemaTypeStructFactory = SchemaTypeStructFactory;