"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaTypeFactory = void 0;

var _Reference = require("../../schema/Reference");

// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;
var SchemaTypeFactory = function SchemaTypeFactory() {
  return {
    fields: function () {
      return {};
    }(),
    is_a: function () {
      return null;
    }(),
    named: (0, _Reference.ReferenceFactory)(),
    options: function () {
      return [];
    }(),
    tags: function () {
      return [];
    }()
  };
};

exports.SchemaTypeFactory = SchemaTypeFactory;