version: 2
jobs:
  build:
    docker:
      - image: lnl7/nix:2019-03-01

    steps:
      - run: |
          nix-env -i coreutils git openssh gnutar gzip rsync bash go
      - checkout
      - run: |
          cd idol
          ./.circleci/build.sh
