// DO NOT EDIT
// This file was generated by idol_graphql_queries, any changes will be overwritten when idol_graphql_queries is run again.;
import gql from "graphql-tag";

export const TestsBasicTestLiteralStructFragment = gql`
  fragment TestsBasicTestLiteralStructFields on TestsBasicTestLiteralStruct {
    five
    four
    one
    three
    two
  }
`;
