// DO NOT EDIT
// This file was generated by idol_graphql_queries, any changes will be overwritten when idol_graphql_queries is run again.;
import { TestsBasicTestStructInnerFragment } from "./TestStructInner";
import gql from "graphql-tag";

export const TestsBasicTestStructFragment = gql`
  fragment TestsBasicTestStructFields on TestsBasicTestStruct {
    a
    b
    c {
      ...TestsBasicTestStructInnerFields
    }
  }
  ${TestsBasicTestStructInnerFragment}
`;
