# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Literal

TestsBasicLiteralThreeO = float
TestsBasicLiteralThreeO = Literal.of(3.0)
locals()["TestsBasicLiteralThreeO"] = Literal.of(3.0)
