# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Literal

TestsBasicLiteralHello = str
TestsBasicLiteralHello = Literal.of("hello")
locals()["TestsBasicLiteralHello"] = Literal.of("hello")
