# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Literal

TestsBasicLiteralFive = int
TestsBasicLiteralFive = Literal.of(5)
locals()["TestsBasicLiteralFive"] = Literal.of(5)
