# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Literal

TestsBasicLiteral1 = int
TestsBasicLiteral1 = Literal.of(1)
locals()["TestsBasicLiteral1"] = Literal.of(1)
