# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Literal

TestsBasicTestLiteralTop = str
TestsBasicTestLiteralTop = Literal.of("mooo")
locals()["TestsBasicTestLiteralTop"] = Literal.of("mooo")
