# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Struct, Primitive
from .test_struct_inner import (
    TestsBasicTestStructInner as CodegenTestsBasicTestStructInner,
)


class TestsBasicTestStruct(Struct):
    a: str

    b: int

    c: CodegenTestsBasicTestStructInner

    __field_constructors__ = [
        ("a", "a", Primitive.of(str), dict(optional=False)),
        ("b", "b", Primitive.of(int), dict(optional=False)),
        ("c", "c", CodegenTestsBasicTestStructInner, dict(optional=False)),
    ]
