# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Struct, Primitive
from typing import Optional


class TestsBasicTestOptionalField(Struct):
    optional: Optional[str]

    __field_constructors__ = [
        ("optional", "optional", Primitive.of(str), dict(optional=True),)
    ]
