# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Struct, List
from typing import MutableSequence
from .test_atleast_one import (
    TestsBasicTestAtleastOne as CodegenTestsBasicTestAtleastOne,
)


class TestsBasicTestListOfListStruct(Struct):
    list_of_list: MutableSequence[CodegenTestsBasicTestAtleastOne]
    __field_constructors__ = [
        (
            "list_of_list",
            "list_of_list",
            List.of(CodegenTestsBasicTestAtleastOne, dict(atleast_one=False)),
            dict(optional=False),
        )
    ]
