# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass
from typing import List
from .type_struct import SchemaTypeStructDataclass


@dataclass
class SchemaFieldDataclass(object):
    field_name: str = field(default_factory=(lambda: ""))
    tags: List[str] = field(default_factory=list)
    type_struct: SchemaTypeStructDataclass = field(
        default_factory=SchemaTypeStructDataclass
    )
