# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass


@dataclass
class SchemaLiteralDataclass(object):
    bool: bool = field(default_factory=(lambda: False))  # type: ignore
    double: float = field(default_factory=(lambda: 0.0))  # type: ignore
    int: int = field(default_factory=(lambda: 0))  # type: ignore
    string: str = field(default_factory=(lambda: ""))  # type: ignore
