# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass
from typing import Optional
from .literal import SchemaLiteralDataclass
from .primitive_type import SchemaPrimitiveTypeEnum
from .reference import SchemaReferenceDataclass
from .struct_kind import SchemaStructKindEnum


@dataclass
class SchemaTypeStructDataclass(object):
    literal: Optional[SchemaLiteralDataclass] = field(default_factory=(lambda: None))
    primitive_type: SchemaPrimitiveTypeEnum = field(
        default_factory=(lambda: next(iter(SchemaPrimitiveTypeEnum)))
    )
    reference: SchemaReferenceDataclass = field(
        default_factory=SchemaReferenceDataclass
    )
    struct_kind: SchemaStructKindEnum = field(
        default_factory=(lambda: next(iter(SchemaStructKindEnum)))
    )
