# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass
from typing import Optional
from ...schema.literal import Literal
from ...schema.primitive_type import PrimitiveType
from ...schema.reference import Reference
from ...schema.struct_kind import StructKind


@dataclass
class SchemaTypeStructDataclass(object):
    literal: Optional[Literal] = field(default_factory=(lambda: None))  # type: ignore
    primitive_type: PrimitiveType = field(default_factory=(lambda: next(iter(PrimitiveType))))  # type: ignore
    reference: Reference = field(default_factory=Reference)  # type: ignore
    struct_kind: StructKind = field(default_factory=(lambda: next(iter(StructKind))))  # type: ignore
