//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.
import type { TestsBasicTestKindPayload as CodegenTestsBasicTestKindPayload } from "../../tests/basic/TestKind";

export type AllRequiredListOfTestKindPayload = Array<CodegenTestsBasicTestKindPayload>;

export const AllRequiredListOfTestKindFactory = () => [];
