//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;
import type { TestsAbsThreeSideImport2Payload as CodegenTestsAbsThreeSideImport2Payload } from "../../tests/abs/three/SideImport2";
import { TestsAbsThreeSideImport2Factory as CodegenTestsAbsThreeSideImport2Factory } from "../../tests/abs/three/SideImport2";
import type { TestsBasicTestLiteralTopPayload as CodegenTestsBasicTestLiteralTopPayload } from "../../tests/basic/TestLiteralTop";
import type { TestsBasicTestStructPayload as CodegenTestsBasicTestStructPayload } from "../../tests/basic/TestStruct";

export interface AllRequiredTripletOfSideImport2Payload {
  a: CodegenTestsAbsThreeSideImport2Payload;
  b: Array<CodegenTestsBasicTestLiteralTopPayload>;
  c: { [k: string]: CodegenTestsBasicTestStructPayload };
}
export const AllRequiredTripletOfSideImport2Factory: () => AllRequiredTripletOfSideImport2Payload = () => ({
  a: CodegenTestsAbsThreeSideImport2Factory(),
  b: (() => [])(),
  c: (() => ({}))()
});
