# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from marshmallow import Schema
from .literal_five import TestsBasicLiteralFiveField
from .literal_true import TestsBasicLiteralTrueField
from .literal1 import TestsBasicLiteral1Field
from .literal_three_o import TestsBasicLiteralThreeOField
from .literal_hello import TestsBasicLiteralHelloField
from ...__idol__ import wrap_field
from marshmallow.fields import Nested


class TestsBasicTestLiteralStructSchema(Schema):
    five = TestsBasicLiteralFiveField(dump_to="five", load_from="five", allow_none=True)
    four = TestsBasicLiteralTrueField(
        dump_to="four", load_from="four", allow_none=False
    )
    one = TestsBasicLiteral1Field(dump_to="one", load_from="one", allow_none=False)
    three = TestsBasicLiteralThreeOField(
        dump_to="three", load_from="three", allow_none=False
    )
    two = TestsBasicLiteralHelloField(dump_to="two", load_from="two", allow_none=False)


TestsBasicTestLiteralStructField = wrap_field(
    Nested,
    "TestsBasicTestLiteralStructField",
    (lambda: TestsBasicTestLiteralStructSchema),
)
