# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from marshmallow import Schema
from marshmallow.fields import Boolean, Float, Int, Nested
from ...__idol__ import wrap_field


class TestsBasicTestStructInnerSchema(Schema):
    d = Boolean(dump_to="d", load_from="d", allow_none=False)
    e = Float(dump_to="e", load_from="e", allow_none=False)
    f = Int(dump_to="f", load_from="f", allow_none=False)


TestsBasicTestStructInnerField = wrap_field(
    Nested, "TestsBasicTestStructInnerField", (lambda: TestsBasicTestStructInnerSchema)
)
