# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from ...__idol__ import wrap_field
from marshmallow.fields import Dict

TestsBasicTestMapField = wrap_field((lambda: Dict), "TestsBasicTestMapField")
