//  @flow
// DO NOT EDIT
// This file was generated by idol_flow, any changes will be overwritten when idol_flow is run again.;

export type SchemaStructKindPayload = "Scalar" | "Repeated" | "Map";
export const SchemaStructKind: SchemaStructKindPayload = {
  SCALAR: "Scalar",
  REPEATED: "Repeated",
  MAP: "Map"
};
