"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaPrimitiveType = void 0;

var _idol__ = require("../__idol__");

// DO NOT EDIT
// This file was generated by idol_js, any changes will be overwritten when idol_js is run again.;
var SchemaPrimitiveType = {
  INT: "int",
  DOUBLE: "double",
  STRING: "string",
  BOOL: "bool",
  ANY: "any",
  options: ["int", "double", "string", "bool", "any"],
  "default": "int",
  // These methods are implemented via the runtime, stubs exist here for reference.,
  validate: function validate(val) {},
  isValid: function isValid(val) {
    return true;
  },
  expand: function expand(val) {
    return val;
  },
  wrap: function wrap(val) {
    return val;
  },
  unwrap: function unwrap(val) {
    return val;
  }
};
exports.SchemaPrimitiveType = SchemaPrimitiveType;
(0, _idol__.Enum)(SchemaPrimitiveType);