"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FieldFragment = void 0;

var _Field = require("../codegen/schema/Field");

// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
var FieldFragment = _Field.SchemaFieldFragment;
exports.FieldFragment = FieldFragment;