// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
import { SchemaLiteralFragment } from "../codegen/schema/Literal";

export const LiteralFragment = SchemaLiteralFragment;
