"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.LiteralFragment = void 0;

var _Literal = require("../codegen/schema/Literal");

// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
var LiteralFragment = _Literal.SchemaLiteralFragment;
exports.LiteralFragment = LiteralFragment;