"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TypeFragment = void 0;

var _Type = require("../codegen/schema/Type");

// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
var TypeFragment = _Type.SchemaTypeFragment;
exports.TypeFragment = TypeFragment;