// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
import { SchemaTypeStructFragment } from "../codegen/schema/TypeStruct";

export const TypeStructFragment = SchemaTypeStructFragment;
