"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TypeStructFragment = void 0;

var _TypeStruct = require("../codegen/schema/TypeStruct");

// This file was scaffolded by idol_graphql_queries.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql_queries.;
var TypeStructFragment = _TypeStruct.SchemaTypeStructFragment;
exports.TypeStructFragment = TypeStructFragment;