// DO NOT EDIT
// This file was generated by idol_graphql_queries, any changes will be overwritten when idol_graphql_queries is run again.;
import gql from "graphql-tag";

// A reference describes the location of a type in the module system.;
export const SchemaReferenceFragment = gql`
  fragment ReferenceFields on Reference {
    module_name
    qualified_name
    type_name
  }
`;
