// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import {
  TestsBasicTestAtleastOneType as CodegenTestsBasicTestAtleastOneType,
  TestsBasicTestAtleastOneInputType as CodegenTestsBasicTestAtleastOneInputType
} from "../../tests/basic/TestAtleastOne";
import { TestsBasicTestEnumType as CodegenTestsBasicTestEnumType } from "../../tests/basic/TestEnum";
import { TestsBasicTestKindType as CodegenTestsBasicTestKindType } from "../../tests/basic/TestKind";
import {
  AllRequiredListOfTestKindType as CodegenAllRequiredListOfTestKindType,
  AllRequiredListOfTestKindInputType as CodegenAllRequiredListOfTestKindInputType
} from "../required/ListOfTestKind";
import {
  TestsBasicTestListOfListStructType as CodegenTestsBasicTestListOfListStructType,
  TestsBasicTestListOfListStructInputType as CodegenTestsBasicTestListOfListStructInputType
} from "../../tests/basic/TestListOfListStruct";
import {
  TestsBasicTestLiteralStructType as CodegenTestsBasicTestLiteralStructType,
  TestsBasicTestLiteralStructInputType as CodegenTestsBasicTestLiteralStructInputType
} from "../../tests/basic/TestLiteralStruct";
import { TestsBasicTestLiteralTopType as CodegenTestsBasicTestLiteralTopType } from "../../tests/basic/TestLiteralTop";
import {
  TestsBasicTestMapType as CodegenTestsBasicTestMapType,
  TestsBasicTestMapInputType as CodegenTestsBasicTestMapInputType
} from "../../tests/basic/TestMap";
import {
  TestsBasicTestOptionalFieldType as CodegenTestsBasicTestOptionalFieldType,
  TestsBasicTestOptionalFieldInputType as CodegenTestsBasicTestOptionalFieldInputType
} from "../../tests/basic/TestOptionalField";
import {
  TestsBasicTestStructType as CodegenTestsBasicTestStructType,
  TestsBasicTestStructInputType as CodegenTestsBasicTestStructInputType
} from "../../tests/basic/TestStruct";
import {
  AllRequiredTripletOfSideImport2Type as CodegenAllRequiredTripletOfSideImport2Type,
  AllRequiredTripletOfSideImport2InputType as CodegenAllRequiredTripletOfSideImport2InputType
} from "../required/TripletOfSideImport2";
import { GraphQLObjectType, GraphQLInputObjectType } from "graphql";

export const AllOptionalAssembledFields = {
  test_atleast_one: CodegenTestsBasicTestAtleastOneType,

  test_enum: CodegenTestsBasicTestEnumType,

  test_kind: CodegenTestsBasicTestKindType,

  test_list_of: CodegenAllRequiredListOfTestKindType,

  test_list_of_list_struct: CodegenTestsBasicTestListOfListStructType,

  test_literal_struct: CodegenTestsBasicTestLiteralStructType,

  test_literal_top: CodegenTestsBasicTestLiteralTopType,

  test_map: CodegenTestsBasicTestMapType,

  test_optional_field: CodegenTestsBasicTestOptionalFieldType,

  test_struct: CodegenTestsBasicTestStructType,

  test_triplet: CodegenAllRequiredTripletOfSideImport2Type
};
export const AllOptionalAssembledType = new GraphQLObjectType({
  name: "AllOptionalAssembledType",
  description: "",
  fields: { ...AllOptionalAssembledFields }
});
export const AllOptionalAssembledInputFields = {
  test_atleast_one: CodegenTestsBasicTestAtleastOneInputType,

  test_enum: CodegenTestsBasicTestEnumType,

  test_kind: CodegenTestsBasicTestKindType,

  test_list_of: CodegenAllRequiredListOfTestKindInputType,

  test_list_of_list_struct: CodegenTestsBasicTestListOfListStructInputType,

  test_literal_struct: CodegenTestsBasicTestLiteralStructInputType,

  test_literal_top: CodegenTestsBasicTestLiteralTopType,

  test_map: CodegenTestsBasicTestMapInputType,

  test_optional_field: CodegenTestsBasicTestOptionalFieldInputType,

  test_struct: CodegenTestsBasicTestStructInputType,

  test_triplet: CodegenAllRequiredTripletOfSideImport2InputType
};
export const AllOptionalAssembledInputType = new GraphQLInputObjectType({
  name: "AllOptionalAssembledInputType",
  description: "",
  fields: { ...AllOptionalAssembledInputFields }
});
