# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from ...__idol__ import Struct
from ...tests.basic.test_atleast_one import (
    TestsBasicTestAtleastOne as CodegenTestsBasicTestAtleastOne,
)
from ...tests.basic.test_enum import TestsBasicTestEnum as CodegenTestsBasicTestEnum
from ...tests.basic.test_kind import TestsBasicTestKind as CodegenTestsBasicTestKind
from .list_of_test_kind import (
    AllRequiredListOfTestKind as CodegenAllRequiredListOfTestKind,
)
from ...tests.basic.test_list_of_list_struct import (
    TestsBasicTestListOfListStruct as CodegenTestsBasicTestListOfListStruct,
)
from ...tests.basic.test_literal_struct import (
    TestsBasicTestLiteralStruct as CodegenTestsBasicTestLiteralStruct,
)
from ...tests.basic.test_literal_top import (
    TestsBasicTestLiteralTop as CodegenTestsBasicTestLiteralTop,
)
from ...tests.basic.test_map import TestsBasicTestMap as CodegenTestsBasicTestMap
from ...tests.basic.test_optional_field import (
    TestsBasicTestOptionalField as CodegenTestsBasicTestOptionalField,
)
from ...tests.basic.test_struct import (
    TestsBasicTestStruct as CodegenTestsBasicTestStruct,
)
from .triplet_of_side_import2 import (
    AllRequiredTripletOfSideImport2 as CodegenAllRequiredTripletOfSideImport2,
)


class AllRequiredAssembled(Struct):
    test_atleast_one: CodegenTestsBasicTestAtleastOne

    test_enum: CodegenTestsBasicTestEnum

    test_kind: CodegenTestsBasicTestKind

    test_list_of: CodegenAllRequiredListOfTestKind

    test_list_of_list_struct: CodegenTestsBasicTestListOfListStruct

    test_literal_struct: CodegenTestsBasicTestLiteralStruct

    test_literal_top: CodegenTestsBasicTestLiteralTop

    test_map: CodegenTestsBasicTestMap

    test_optional_field: CodegenTestsBasicTestOptionalField

    test_struct: CodegenTestsBasicTestStruct

    test_triplet: CodegenAllRequiredTripletOfSideImport2

    __field_constructors__ = [
        (
            "test_atleast_one",
            "test_atleast_one",
            CodegenTestsBasicTestAtleastOne,
            dict(optional=False),
        ),
        ("test_enum", "test_enum", CodegenTestsBasicTestEnum, dict(optional=False)),
        ("test_kind", "test_kind", CodegenTestsBasicTestKind, dict(optional=False)),
        (
            "test_list_of",
            "test_list_of",
            CodegenAllRequiredListOfTestKind,
            dict(optional=False),
        ),
        (
            "test_list_of_list_struct",
            "test_list_of_list_struct",
            CodegenTestsBasicTestListOfListStruct,
            dict(optional=False),
        ),
        (
            "test_literal_struct",
            "test_literal_struct",
            CodegenTestsBasicTestLiteralStruct,
            dict(optional=False),
        ),
        (
            "test_literal_top",
            "test_literal_top",
            CodegenTestsBasicTestLiteralTop,
            dict(optional=False),
        ),
        ("test_map", "test_map", CodegenTestsBasicTestMap, dict(optional=False)),
        (
            "test_optional_field",
            "test_optional_field",
            CodegenTestsBasicTestOptionalField,
            dict(optional=False),
        ),
        (
            "test_struct",
            "test_struct",
            CodegenTestsBasicTestStruct,
            dict(optional=False),
        ),
        (
            "test_triplet",
            "test_triplet",
            CodegenAllRequiredTripletOfSideImport2,
            dict(optional=False),
        ),
    ]
