# DO NOT EDIT
# This file was generated by idol_py, any changes will be lost when idol_py is rerun again
from typing import MutableSequence
from ...tests.basic.test_kind import TestsBasicTestKind as CodegenTestsBasicTestKind
from ...__idol__ import List

AllRequiredListOfTestKind = MutableSequence[CodegenTestsBasicTestKind]
AllRequiredListOfTestKind = List.of(CodegenTestsBasicTestKind, dict(atleast_one=True))
locals()["AllRequiredListOfTestKind"] = List.of(
    CodegenTestsBasicTestKind, dict(atleast_one=True)
)
