# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from marshmallow import Schema
from marshmallow.fields import String, List, Nested
from .type_struct import SchemaTypeStructField
from importlib import import_module
from ..__idol__ import wrap_field


class SchemaFieldSchema(Schema):
    field_name = String(dump_to="field_name", load_from="field_name")
    tags = List(String(), dump_to="tags", load_from="tags")
    type_struct = SchemaTypeStructField(dump_to="type_struct", load_from="type_struct")


SchemaFieldField = wrap_field(
    Nested,
    "SchemaFieldField",
    (lambda: import_module("...schema.field", __package__).Field),
)
