# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from marshmallow import Schema
from marshmallow.fields import String, Nested
from importlib import import_module
from ..__idol__ import wrap_field


class SchemaReferenceSchema(Schema):
    """
    A reference describes the location of a type in the module system.
    """

    # Just the module name
    module_name = String(dump_to="module_name", load_from="module_name")
    # The module_name.type_name string
    qualified_name = String(dump_to="qualified_name", load_from="qualified_name")
    # Just the type name
    type_name = String(dump_to="type_name", load_from="type_name")


SchemaReferenceField = wrap_field(
    Nested,
    "SchemaReferenceField",
    (lambda: import_module("...schema.reference", __package__).Reference),
)
