# DO NOT EDIT
# This file was generated by idol_mar, any changes will be lost when idol_mar is rerun again
from marshmallow import Schema
from .literal import SchemaLiteralField
from .primitive_type import SchemaPrimitiveTypeField
from .reference import SchemaReferenceField
from .struct_kind import SchemaStructKindField
from importlib import import_module
from ..__idol__ import wrap_field
from marshmallow.fields import Nested


class SchemaTypeStructSchema(Schema):
    literal = SchemaLiteralField(dump_to="literal", load_from="literal")
    primitive_type = SchemaPrimitiveTypeField(
        dump_to="primitive_type", load_from="primitive_type"
    )
    reference = SchemaReferenceField(dump_to="reference", load_from="reference")
    struct_kind = SchemaStructKindField(dump_to="struct_kind", load_from="struct_kind")


SchemaTypeStructField = wrap_field(
    Nested,
    "SchemaTypeStructField",
    (lambda: import_module("...schema.type_struct", __package__).TypeStruct),
)
