// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { LiteralTypeOf } from "../../__idol_graphql__";

export const TestsBasicLiteral1Type = LiteralTypeOf(
  "TestsBasicLiteral1",
  1,
  ""
);
