// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { GraphQLEnumType } from "graphql";
import { wrapValues } from "../../__idol_graphql__";

export const TestsBasicTestEnum = { A: "a", B: "b", C: "c" };
export const TestsBasicTestEnumType = new GraphQLEnumType({
  name: "TestsBasicTestEnumType",
  description: "",
  values: wrapValues(TestsBasicTestEnum)
});
