// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import {
  GraphQLString,
  GraphQLInt,
  GraphQLObjectType,
  GraphQLInputObjectType
} from "graphql";
import {
  TestsBasicTestStructInnerType as CodegenTestsBasicTestStructInnerType,
  TestsBasicTestStructInnerInputType as CodegenTestsBasicTestStructInnerInputType
} from "./TestStructInner";

export const TestsBasicTestStructFields = {
  a: GraphQLString,

  b: GraphQLInt,

  c: CodegenTestsBasicTestStructInnerType
};
export const TestsBasicTestStructType = new GraphQLObjectType({
  name: "TestsBasicTestStructType",
  description: "",
  fields: { ...TestsBasicTestStructFields }
});
export const TestsBasicTestStructInputFields = {
  a: GraphQLString,

  b: GraphQLInt,

  c: CodegenTestsBasicTestStructInnerInputType
};
export const TestsBasicTestStructInputType = new GraphQLInputObjectType({
  name: "TestsBasicTestStructInputType",
  description: "",
  fields: { ...TestsBasicTestStructInputFields }
});
