// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import {
  GraphQLBoolean,
  GraphQLFloat,
  GraphQLInt,
  GraphQLObjectType,
  GraphQLInputObjectType
} from "graphql";

export const TestsBasicTestStructInnerFields = {
  d: GraphQLBoolean,

  e: GraphQLFloat,

  f: GraphQLInt
};
export const TestsBasicTestStructInnerType = new GraphQLObjectType({
  name: "TestsBasicTestStructInnerType",
  description: "",
  fields: { ...TestsBasicTestStructInnerFields }
});
export const TestsBasicTestStructInnerInputFields = {
  d: GraphQLBoolean,

  e: GraphQLFloat,

  f: GraphQLInt
};
export const TestsBasicTestStructInnerInputType = new GraphQLInputObjectType({
  name: "TestsBasicTestStructInnerInputType",
  description: "",
  fields: { ...TestsBasicTestStructInnerInputFields }
});
