// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { GraphQLList } from "graphql";
import { TestsBasicTestKindType as CodegenTestsBasicTestKindType } from "./TestKind";

export const TestsBasicTestAtleastOneType = new GraphQLList(
  CodegenTestsBasicTestKindType
);

export const TestsBasicTestAtleastOneInputType = new GraphQLList(
  CodegenTestsBasicTestKindType
);
