// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.
import { GraphQLString } from "graphql";

export const TestsBasicTestKindType = GraphQLString;
