// This file was scaffolded by idol_graphql.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_graphql.;
import { SchemaPrimitiveTypeType } from "../codegen/schema/PrimitiveType";

export const PrimitiveTypeType = SchemaPrimitiveTypeType;
