# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from enum import Enum


class TestsBasicTestEnumEnum(Enum):
    A = "a"
    B = "b"
    C = "c"
