# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from typing import Mapping
from .test_atleast_one import TestAtleastOne

TestMap = Mapping[str, TestAtleastOne]
