# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass
from .test_struct_inner import TestsBasicTestStructInnerDataclass


@dataclass
class TestsBasicTestStructDataclass(object):
    a: str = field(default_factory=(lambda: ""))  # type: ignore
    b: int = field(default_factory=(lambda: 0))  # type: ignore
    c: TestsBasicTestStructInnerDataclass = field(default_factory=TestsBasicTestStructInnerDataclass)  # type: ignore
