# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass


@dataclass
class TestsBasicTestStructInnerDataclass(object):
    d: bool = field(default_factory=(lambda: False))  # type: ignore
    e: float = field(default_factory=(lambda: 0.0))  # type: ignore
    f: int = field(default_factory=(lambda: 0))  # type: ignore
