# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from dataclasses import field, dataclass
from typing import Optional
from .literal_five import LiteralFive
from .literal_true import LiteralTrue
from .literal1 import Literal1
from .literal_three_o import LiteralThreeO
from .literal_hello import LiteralHello


@dataclass
class TestsBasicTestLiteralStructDataclass(object):
    five: Optional[LiteralFive] = field(default_factory=(lambda: None))
    four: LiteralTrue = field(default_factory=(lambda: True))
    one: Literal1 = field(default_factory=(lambda: 1))
    three: LiteralThreeO = field(default_factory=(lambda: 3.0))
    two: LiteralHello = field(default_factory=(lambda: "hello"))
