// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.
import { LiteralType as ScaffoldLiteralType } from "../../schema/Literal";
import { PrimitiveTypeType as ScaffoldPrimitiveTypeType } from "../../schema/PrimitiveType";
import { ReferenceType as ScaffoldReferenceType } from "../../schema/Reference";
import { StructKindType as ScaffoldStructKindType } from "../../schema/StructKind";

export const SchemaTypeStructFields = {
  literal: { type: ScaffoldLiteralType, description: "" },
  primitive_type: { type: ScaffoldPrimitiveTypeType, description: "" },
  reference: { type: ScaffoldReferenceType, description: "" },
  struct_kind: { type: ScaffoldStructKindType, description: "" }
};
