"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SchemaFieldFields = void 0;

var _graphql = require("graphql");

var _TypeStruct = require("../../schema/TypeStruct");

// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.
var SchemaFieldFields = {
  field_name: {
    type: _graphql.GraphQLString,
    description: ""
  },
  tags: {
    type: new _graphql.GraphQLList(_graphql.GraphQLString),
    description: ""
  },
  type_struct: {
    type: _TypeStruct.TypeStructType,
    description: ""
  }
};
exports.SchemaFieldFields = SchemaFieldFields;