// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { GraphQLString } from "graphql";
import { Anything } from "../__idol_graphql__";

// Metadata contained about a module.;
export const SchemaModuleFields = {
  module_name: GraphQLString,

  types_by_name: Anything
};
