// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { GraphQLEnumType } from "graphql";
import { wrapValues } from "../__idol_graphql__";

export const SchemaPrimitiveType = {
  INT: "int",
  DOUBLE: "double",
  STRING: "string",
  BOOL: "bool",
  ANY: "any"
};
export const SchemaPrimitiveTypeType = new GraphQLEnumType({
  name: "PrimitiveTypeType",
  description: "",
  values: wrapValues(SchemaPrimitiveType)
});
