// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
import { GraphQLString } from "graphql";

// A reference describes the location of a type in the module system.;
export const SchemaReferenceFields = {
  // Just the module name,
  module_name: GraphQLString,
  // The module_name.type_name string,
  qualified_name: GraphQLString,
  // Just the type name,
  type_name: GraphQLString
};
