"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.StructKindType = exports.SchemaStructKind = void 0;

var _graphql = require("graphql");

var _idol_graphql__ = require("../__idol_graphql__");

// DO NOT EDIT
// This file was generated by idol_graphql, any changes will be overwritten when idol_graphql is run again.;
// Scalars are non contained values
// Repeated are homogenous lists.  They can be upgraded or downgraded to and from Scalars.
// A repeated is indicated in a TypeDec by ending with '[]'
// Maps are homogenous 'dictionaries', whose key is always a string, mapping to js objects.
// A map is indicated in a TypeDec by ending with '{}';
var SchemaStructKind = {
  SCALAR: "Scalar",
  REPEATED: "Repeated",
  MAP: "Map"
};
exports.SchemaStructKind = SchemaStructKind;
var StructKindType = new _graphql.GraphQLEnumType({
  name: "StructKind",
  description: "Scalars are non contained values\nRepeated are homogenous lists.  They can be upgraded or downgraded to and from Scalars.\nA repeated is indicated in a TypeDec by ending with '[]'\nMaps are homogenous 'dictionaries', whose key is always a string, mapping to js objects.\nA map is indicated in a TypeDec by ending with '{}'",
  values: (0, _idol_graphql__.wrapValues)(SchemaStructKind)
});
exports.StructKindType = StructKindType;