# DO NOT EDIT
# This file was generated by idol_data, any changes will be lost when idol_data is rerun again
from typing import List
from ...tests.basic.test_kind import TestKind

ListOfTestKind = List[TestKind]
