/*
DO NOT EDIT
This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
*/
import { List } from "../../__idol__";
import { TestsBasicTestKind as CodegenTestsBasicTestKind } from "./TestKind";

export const TestsBasicTestAtleastOne = List.of(CodegenTestsBasicTestKind, {
  atleastOne: true
});
