// DO NOT EDIT
// This file was generated by idol_js, any changes will be overwritten when idol_js is run again.;
import { Map } from "../../__idol__";
import { TestsBasicTestAtleastOne as CodegenTestsBasicTestAtleastOne } from "./TestAtleastOne";

export const TestsBasicTestMap = Map.of(CodegenTestsBasicTestAtleastOne, {});
