// DO NOT EDIT
// This file was generated by idol_js, any changes will be overwritten when idol_js is run again.
import { List, Struct } from "../../__idol__";
import { TestsBasicTestAtleastOne as CodegenTestsBasicTestAtleastOne } from "./TestAtleastOne";

export class TestsBasicTestListOfListStruct {
  constructor(val) {
    this._original = val;
  }
  // These methods are implemented via the runtime, stubs exist here for reference.
  static validate(val) {}
  static isValid(val) {
    return true;
  }
  static expand(val) {
    return val;
  }
  static unwrap(val) {
    return val;
  }
  static wrap(val) {
    return null;
  }

  get list_of_list() {
    return List.of(CodegenTestsBasicTestAtleastOne, { atleastOne: false }).wrap(
      this._original["list_of_list"]
    );
  }
  set list_of_list(val) {
    this._original["list_of_list"] = List.of(CodegenTestsBasicTestAtleastOne, {
      atleastOne: false
    }).unwrap(val);
  }
  get listOfList() {
    return this.list_of_list;
  }
  set listOfList(val) {
    this.list_of_list = val;
  }
}

Struct(TestsBasicTestListOfListStruct, [
  {
    fieldName: "list_of_list",
    type: List.of(CodegenTestsBasicTestAtleastOne, { atleastOne: false }),
    optional: false
  }
]);
