// DO NOT EDIT
// This file was generated by idol_graphql_queries, any changes will be overwritten when idol_graphql_queries is run again.;
import { TestsAbsThreeSideImport2Fragment } from "../../tests/abs/three/SideImport2";
import gql from "graphql-tag";

export const AllRequiredTripletOfSideImport2Fragment = gql`
  fragment AllRequiredTripletOfSideImport2Fields on AllRequiredTripletOfSideImport2 {
    a {
      ...TestsAbsThreeSideImport2Fields
    }
    b
    c
  }
  ${TestsAbsThreeSideImport2Fragment}
`;
