[ModuleDec]
is_a = "TypeDec{}"

[FieldDec]
is_a = "string[]"

[FieldsDec]
is_a = "FieldDec{}"

[TypeDec]
fields.enum = "string[]"
fields.is_a = "string[]"
fields.fields = "FieldsDec?"
fields.tags = "string[]"

fields.variance = "Variance"

[Variance]
enum = ["Covariant", "Contravariant"]

[ModuleInclude]
fields.from = "string"
fields.matching = "string"

[ModuleIncludes]
is_a = "ModuleInclude[]"

[IncludesDec]
fields.includes = "ModuleIncludes"
