//  @flow
// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
import type { SchemaFieldPayload } from "../codegen/schema/Field";
import { SchemaFieldFactory } from "../codegen/schema/Field";

export interface FieldPayload extends SchemaFieldPayload {}
export const FieldFactory: () => FieldPayload = SchemaFieldFactory;
