//  @flow
// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
import type { SchemaLiteralPayload } from "../codegen/schema/Literal";
import { SchemaLiteralFactory } from "../codegen/schema/Literal";

export interface LiteralPayload extends SchemaLiteralPayload {}
export const LiteralFactory: () => LiteralPayload = SchemaLiteralFactory;
