//  @flow
// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
import type { SchemaReferencePayload } from "../codegen/schema/Reference";
import { SchemaReferenceFactory } from "../codegen/schema/Reference";

export interface ReferencePayload extends SchemaReferencePayload {}
export const ReferenceFactory: () => ReferencePayload = SchemaReferenceFactory;
