//  @flow
// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
import type { SchemaTypeStructPayload } from "../codegen/schema/TypeStruct";
import { SchemaTypeStructFactory } from "../codegen/schema/TypeStruct";

export interface TypeStructPayload extends SchemaTypeStructPayload {}
export const TypeStructFactory: () => TypeStructPayload = SchemaTypeStructFactory;
