import {
    Enum as Enum_,
    Struct as Struct_,
    List as List_,
    Map as Map_,
    Literal as Literal_,
    Primitive as Primitive_,
} from "./../../__idol__"
// DO NOT EDIT THIS FILE
// This file is generated via idol_js.js.  You can either subclass these types
// in your own module file or update the relevant model.toml file and regenerate.

export function SideImport2(val) {
    return SideImport2.wrap.apply(this, arguments)
}

Struct_(SideImport2, [
    ["sideImport2", "side_import2", Primitive_.of("int")],
]);

SideImport2.metadata = {"dependencies":[],"fields":{"side_import2":{"field_name":"side_import2","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"int","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Scalar"}}},"is_a":null,"named":{"module_name":"tests.abs.three","qualified_name":"tests.abs.three.SideImport2","type_name":"SideImport2"},"options":[],"tags":[],"type_vars":[]};
