import {
    Enum as Enum_,
    Struct as Struct_,
    List as List_,
    Map as Map_,
    Literal as Literal_,
    Primitive as Primitive_,
} from "./../../__idol__"
// DO NOT EDIT THIS FILE
// This file is generated via idol_js.js.  You can either subclass these types
// in your own module file or update the relevant model.toml file and regenerate.

export function SideImport(val) {
    return SideImport.wrap.apply(this, arguments)
}

Struct_(SideImport, [
    ["sideImport", "side_import", Primitive_.of("string")],
]);

SideImport.metadata = {"dependencies":[],"fields":{"side_import":{"field_name":"side_import","tags":[],"type_struct":{"literal":null,"parameters":[],"primitive_type":"string","reference":{"module_name":"","qualified_name":"","type_name":""},"struct_kind":"Scalar"}}},"is_a":null,"named":{"module_name":"tests.abs.two","qualified_name":"tests.abs.two.SideImport","type_name":"SideImport"},"options":[],"tags":[],"type_vars":[]};
