"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FieldFactory = void 0;

var _Field = require("../codegen/schema/Field");

// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
var FieldFactory = _Field.SchemaFieldFactory;
exports.FieldFactory = FieldFactory;