"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ModuleFactory = void 0;

var _Module = require("../codegen/schema/Module");

// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
var ModuleFactory = _Module.SchemaModuleFactory;
exports.ModuleFactory = ModuleFactory;