"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ReferenceFactory = void 0;

var _Reference = require("../codegen/schema/Reference");

// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
var ReferenceFactory = _Reference.SchemaReferenceFactory;
exports.ReferenceFactory = ReferenceFactory;