"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.StructKindFactory = exports.StructKind = void 0;

var _StructKind = require("../codegen/schema/StructKind");

// This file was scaffolded by idol_flow.  Feel free to edit as you please.  It can be regenerated by deleting the file and rerunning idol_flow.;
var StructKind = _StructKind.SchemaStructKind;
exports.StructKind = StructKind;
var StructKindFactory = _StructKind.SchemaStructKindFactory;
exports.StructKindFactory = StructKindFactory;